### PR TITLE
Switch to GH Pages domain

### PR DESCRIPTION
**Pull request by Airblader**
This pull request relates to or closes the following issues:

I have verified that…
- [X] the commits in this pull request follow the [conventionalcommits](https://www.conventionalcommits.org) pattern
- [X] tests have been updated or added
- [X] documentation has been updated to reflect the changes made

### CODE REVIEW

**Comment by Airblader** [comment]
@maxhbr I can't merge my own PR because it needs an approval, but I cannot approve it. 🙈

**Review by maxhbr — APPROVED** [review]
LGTM

**Comment by Airblader** [comment]
Screenshot 2022-11-07 at 09 04 30
Screenshot 2022-11-07 at 09 04 37

🤔

**Comment by maxhbr** [comment]
The branch protection rules do not just require `singed-off`-commits but also gpg or ssh signed commits. I do not know who has set up this, but seems to be overkill :).

**Comment by Airblader** [comment]
Indeed. Can you change that? I do not have permission to do so.

**Comment by maxhbr** [comment]
DONE

**Comment by Airblader** [comment]
Thanks!

**Pull request merged**
